risk_map = {
    "North America": {
        "Alaska": {"neighbors": ["Northwest Territory", "Alberta", "Kamchatka"], "continent": "North America"},
        "Northwest Territory": {"neighbors": ["Alaska", "Greenland", "Alberta", "Ontario"], "continent": "North America"},
        "Greenland": {"neighbors": ["Northwest Territory", "Ontario", "Quebec", "Iceland"], "continent": "North America"},
        "Alberta": {"neighbors": ["Alaska", "Northwest Territory", "Ontario", "Western United States"], "continent": "North America"},
        "Ontario": {"neighbors": ["Northwest Territory", "Alberta", "Western United States", "Eastern United States", "Quebec", "Greenland"], "continent": "North America"},
        "Quebec": {"neighbors": ["Ontario", "Eastern United States", "Greenland"], "continent": "North America"},
        "Western United States": {"neighbors": ["Alberta", "Ontario", "Eastern United States", "Central America"], "continent": "North America"},
        "Eastern United States": {"neighbors": ["Ontario", "Quebec", "Western United States", "Central America"], "continent": "North America"},
        "Central America": {"neighbors": ["Western United States", "Eastern United States", "Venezuela"], "continent": "North America"},
    },
    "South America": {
        "Venezuela": {"neighbors": ["Central America", "Brazil", "Peru"], "continent": "South America"},
        "Brazil": {"neighbors": ["Venezuela", "Peru", "Argentina", "North Africa"], "continent": "South America"},
        "Peru": {"neighbors": ["Venezuela", "Brazil", "Argentina"], "continent": "South America"},
        "Argentina": {"neighbors": ["Peru", "Brazil"], "continent": "South America"},
    },
    "Europe": {
        "Iceland": {"neighbors": ["Greenland", "Great Britain", "Scandinavia"], "continent": "Europe"},
        "Great Britain": {"neighbors": ["Iceland", "Scandinavia", "Northern Europe", "Western Europe"], "continent": "Europe"},
        "Scandinavia": {"neighbors": ["Iceland", "Great Britain", "Northern Europe", "Ukraine"], "continent": "Europe"},
        "Northern Europe": {"neighbors": ["Scandinavia", "Great Britain", "Western Europe", "Southern Europe", "Ukraine"], "continent": "Europe"},
        "Western Europe": {"neighbors": ["Great Britain", "Northern Europe", "Southern Europe", "North Africa"], "continent": "Europe"},
        "Southern Europe": {"neighbors": ["Western Europe", "Northern Europe", "Ukraine", "Middle East", "North Africa", "Egypt"], "continent": "Europe"},
        "Ukraine": {"neighbors": ["Scandinavia", "Northern Europe", "Southern Europe", "Ural", "Afghanistan", "Middle East"], "continent": "Europe"},
    },
    "Africa": {
        "North Africa": {"neighbors": ["Western Europe", "Brazil", "Egypt", "East Africa", "Congo", "Southern Europe"], "continent": "Africa"},
        "Egypt": {"neighbors": ["North Africa", "Southern Europe", "Middle East", "East Africa"], "continent": "Africa"},
        "East Africa": {"neighbors": ["Egypt", "North Africa", "Congo", "South Africa", "Madagascar", "Middle East"], "continent": "Africa"},
        "Congo": {"neighbors": ["North Africa", "East Africa", "South Africa"], "continent": "Africa"},
        "South Africa": {"neighbors": ["Congo", "East Africa", "Madagascar"], "continent": "Africa"},
        "Madagascar": {"neighbors": ["East Africa", "South Africa"], "continent": "Africa"},
    },
    "Asia": {
        "Ural": {"neighbors": ["Ukraine", "Siberia", "China", "Afghanistan"], "continent": "Asia"},
        "Siberia": {"neighbors": ["Ural", "Yakutsk", "Irkutsk", "Mongolia", "China"], "continent": "Asia"},
        "Yakutsk": {"neighbors": ["Siberia", "Kamchatka", "Irkutsk"], "continent": "Asia"},
        "Kamchatka": {"neighbors": ["Yakutsk", "Irkutsk", "Mongolia", "Japan", "Alaska"], "continent": "Asia"},
        "Irkutsk": {"neighbors": ["Siberia", "Yakutsk", "Kamchatka", "Mongolia"], "continent": "Asia"},
        "Mongolia": {"neighbors": ["Irkutsk", "Kamchatka", "Japan", "China", "Siberia"], "continent": "Asia"},
        "Japan": {"neighbors": ["Kamchatka", "Mongolia"], "continent": "Asia"},
        "Afghanistan": {"neighbors": ["Ukraine", "Ural", "China", "India", "Middle East"], "continent": "Asia"},
        "China": {"neighbors": ["Ural", "Siberia", "Mongolia", "India", "Siam", "Afghanistan"], "continent": "Asia"},
        "India": {"neighbors": ["Afghanistan", "China", "Middle East", "Siam"], "continent": "Asia"},
        "Siam": {"neighbors": ["India", "China", "Indonesia"], "continent": "Asia"},
        "Middle East": {"neighbors": ["Ukraine", "Southern Europe", "Egypt", "East Africa", "India", "Afghanistan"], "continent": "Asia"},
    },
    "Australia": {
        "Indonesia": {"neighbors": ["Siam", "New Guinea", "Western Australia"], "continent": "Australia"},
        "New Guinea": {"neighbors": ["Indonesia", "Eastern Australia", "Western Australia"], "continent": "Australia"},
        "Western Australia": {"neighbors": ["Indonesia", "New Guinea", "Eastern Australia"], "continent": "Australia"},
        "Eastern Australia": {"neighbors": ["New Guinea", "Western Australia"], "continent": "Australia"},
    }
}
